# Generated by Django 4.0.4 on 2022-05-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Жанр')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Фильм')),
                ('content', models.TextField(verbose_name='Описание фильма')),
                ('year', models.PositiveIntegerField(verbose_name='Год выхода')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Добавлен')),
                ('genre', models.ManyToManyField(to='main.genres', verbose_name='Жанры')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
                'ordering': ['-published'],
            },
        ),
    ]
