# Generated by Django 4.0.4 on 2022-05-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='img',
            field=models.ImageField(null=True, upload_to='uploads'),
        ),
    ]
