# Generated by Django 4.0.4 on 2022-05-15 14:49

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_films_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='video',
            field=embed_video.fields.EmbedVideoField(null=True, verbose_name='URL Фильма'),
        ),
        migrations.AlterField(
            model_name='films',
            name='img',
            field=models.ImageField(null=True, upload_to='uploads', verbose_name='Картинка'),
        ),
    ]
